# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]

ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

"ctrl-y" = 'split horizontal'
"ctrl-z" = 'split vertical'

ctrl-f = 'fullscreen'

"ctrl-shift-w" = 'layout v_accordion' # 'layout stacking' in i3
# comment one out as I'm running out of available hotkeys
# "ctrl-w" = 'layout h_accordion' # 'layout tabbed' in i3 
"ctrl-shift-e" = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
#ctrl-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# ctrl-a = 'focus parent'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'

cmd-ctrl-shift-h = 'move-workspace-to-monitor --wrap-around prev'
cmd-ctrl-shift-l = 'move-workspace-to-monitor --wrap-around next'

ctrl-shift-c = 'reload-config'

ctrl-r = 'mode resize'


[[on-window-detected]]
if.app-name-regex-substring = 'chrome'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'goland'
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'wezterm'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
check-further-callbacks = true
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = 'zoom'
check-further-callbacks = true
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-name-regex-substring = 'notes'
check-further-callbacks = true
run = ['move-node-to-workspace 8']


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

